
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitystudy
    username: root
    password: 991911
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 242883719042-j8o7kpfeql2vua2ef69tldaam7kh6f4j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


jwt:
  secret:
    access: Z29sZGdneXVsLXRvZG9hcnktand0LXRlc3QtZ29sZGdneXVsLXRvZG9hcnktand0LXRlc3QtZ29sZGdneXVsLXRvZG9hcnktand0LXRlc3QK
    refresh: Z29sZGdneXVsLXRvZG9hcnktand0LXRlc3QtZ29sZGdneXVsLXRvZGZ29sZGdneXVsLXRvZG9hcnktand0LXRlc3QtZ29sZGdneXVsLXRvZG
  time: # milliseconds
    access: 7200000 # 2??
    refresh: 7776000000 # 90?